paths:
  data_dir: data
  duckdb_path: data/nfl.duckdb
mlflow:
  tracking_uri: ./mlruns
  experiment: Default
  hygiene:
    dry_run: true
    delete_artifacts: false
    retention:
      max_age_days: 180
      keep_last_runs: 20
      keep_top_runs: 10
      metric: holdout_brier
      metric_goal: min
      protect_promoted: true
features:
  windows:
    short: 4
    mid: 8
monitoring:
  retrain_triggers:
    brier_window_weeks: 4
    brier_deterioration_pct: 0.1
    psi_threshold: 0.2
    psi_feature_count: 5
training:
  playoffs:
    mode: regular_only
